name: 'Terraform reusable Plan/Apply'

on:
  workflow_call:
    inputs:
      root_dir_path:
        description: Root directory of terraform-related files
        required: true
        type: string
      root_module_path:
        description: Directory where Main.tf is stored
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        description: AWS Account ID
        required: true
      GITHUBACTIONS_ROLE:
        description: GITHUBACTIONS_ROLE
        required: true
      TFSTATE_BUCKET:
        description: TFSTATE_BUCKET
        required: true
defaults:                                         # デフォルトシェル
  run:
    shell: bash


env:
  ROOT_DIR_PATH: ${{ inputs.root_dir_path }}
  ROOT_MODULE_PATH: ${{ inputs.root_module_path }}
  TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ASSUME_ROLE: ${{ secrets.GITHUBACTIONS_ROLE }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set AWS Credential
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ASSUME_ROLE }}
        aws-region: ap-northeast-1

    - name: Get Terraform Version
      id: tf-version
      run: |
        echo "TERRAFORM_VERSION=$(cat .terraform-version)" >> "$GITHUB_OUTPUT"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.tf-version.outputs.TERRAFORM_VERSION }}

    - name: Terraform Init
      run: |
        terraform init -backend-config="bucket=${{ env.TFSTATE_BUCKET }}"
      working-directory: ${{ env.ROOT_MODULE_PATH }}

    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: ${{ env.ROOT_MODULE_PATH }}

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ${{ env.ROOT_MODULE_PATH }}
