name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      destroy-target-path:
        type: string
        required: true
        description: 'Destroy the Terraform main.tf path'
defaults:                                         # デフォルトシェル
  run:
    shell: bash
concurrency:                                      # 自動キャンセル
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ROOT_MODULE_PATH: ${{ github.event.inputs.destroy-target-path }}
  APPLY_ROLE_ARN: ${{ secrets.GITHUBACTIONS_ROLE }}
  TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set AWS Credential
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.APPLY_ROLE_ARN }}
        aws-region: ap-northeast-1

    - name: Get Terraform Version
      id: tf-version
      run: |
        echo "TERRAFORM_VERSION=$(cat .terraform-version)" >> "$GITHUB_OUTPUT"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.tf-version.outputs.TERRAFORM_VERSION }}
        terraform_wrapper: false

    - name: Terraform Init
      run: |
        terraform init -backend-config="bucket=${{ env.TFSTATE_BUCKET }}"
      working-directory: ${{ env.ROOT_MODULE_PATH }}


    - name: Terraform Destroy
      run: |
        terraform destroy -auto-approve
      working-directory: ${{ env.ROOT_MODULE_PATH }}
